import { SearchIndexAdditonalFieldType } from './interfaces/SearchIndexAdditonalFieldType';
import { Settings } from './interfaces/Settings';

export  class SearchFacetExtensions {
    static isValueFacet(settings: Settings) {
        if (settings.RangeType === this.AutoGeneratedFacet) {
            if (settings.FacetType === SearchIndexAdditonalFieldType.DateAndTime) {
                // UX: When no data step is set - the Date field should be displayed as interval facet with a day interval.
                return false;
            }

            if (settings.FacetType === SearchIndexAdditonalFieldType.NumberWhole
                || settings.FacetType === SearchIndexAdditonalFieldType.NumberDecimal) {
                // UX: When no number step is set - the Number field should be displayd as a value facet.
                return settings.NumberStep == null;
            }

            return true;
        }

        return false;
    }

    static AutoGeneratedFacet = 0;
}
